name: PR Check (Next.js + Vercel)

on:
  pull_request:
    branches: [main]   # only run when targeting main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Type check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build
